[package]
name = "backbone-ntruplr"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "NTRU LPRime implementation: KEM based on NTRU lattices."
categories = ["cryptography", "no-std"]
keywords = ["ntruplr", "ntru-lprime", "kem", "post-quantum", "lattice-based"]
exclude = ["tests/"]

[lints]
workspace = true

[dependencies]
backbone-pqcrypto-internals = { version = "0.2.0", path = "../backbone-pqcrypto-internals", default-features = false }
sha2 = { workspace = true }
sha3 = { workspace = true }
aes = { version = "0.9", features = ["zeroize"] }
ctr = "0.10"
zeroize = { workspace = true }
subtle = { workspace = true }
getrandom = { workspace = true, default-features = false }

[features]
default = ["std", "zeroize"]
std = [
  "alloc",
  "sha2/std",
  "sha3/std",
  "zeroize/alloc",
  "backbone-pqcrypto-internals/std",
  "getrandom/std",
]
alloc = ["zeroize/alloc"]
zeroize = ["backbone-pqcrypto-internals/zeroize"]
