[package]
name = "pqcrypto-sphincs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "SPHINCS+ (FIPS 205) implementation: Stateless Hash-Based Digital Signature Standard"
categories = ["cryptography", "no-std"]
keywords = ["sphincs+", "fips-205", "signature", "post-quantum", "hash-based"]

[lints]
workspace = true

[dependencies]
pqcrypto-utils = { path = "../pqcrypto-utils", default-features = false }
zeroize = { workspace = true }
sha3 = { workspace = true }
sha2 = { workspace = true }
getrandom = { workspace = true }

[features]
default = ["std", "zeroize"]
std = [
  "alloc",
  "sha2/std",
  "sha3/std",
  "zeroize/alloc",
  "pqcrypto-utils/std",
  "getrandom/std",
]
alloc = ["zeroize/alloc"]
zeroize = ["pqcrypto-utils/zeroize"]

[dev-dependencies]
hex = "0.4"
