[package]
name = "backbone-mceliece"
version = "0.1.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Classic McEliece KEM implementation: code-based post-quantum key encapsulation."
categories = ["cryptography", "no-std"]
keywords = ["mceliece", "kem", "post-quantum", "code-based", "cryptography"]
exclude = ["tests/"]

[lints]
workspace = true

[dependencies]
safe_arch = { version = "1", optional = true }
backbone-pqcrypto-internals = { version = "0.2.0", path = "../backbone-pqcrypto-internals", default-features = false }
zeroize = { workspace = true }
sha3 = { workspace = true, default-features = false }
getrandom = { workspace = true, default-features = false }
subtle = { workspace = true }

[dev-dependencies]
sha2 = { workspace = true, default-features = false }

[features]
default = ["std", "zeroize"]
std = [
  "alloc",
  "sha3/std",
  "zeroize/alloc",
  "backbone-pqcrypto-internals/std",
  "getrandom/std",
]
alloc = ["zeroize/alloc"]
zeroize = ["backbone-pqcrypto-internals/zeroize"]
simd = ["safe_arch"]
