[package]
name = "backbone-ml-kem"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "ML-KEM (FIPS 203) implementation: Module-Lattice-Based Key Encapsulation Mechanism."
categories = ["cryptography", "no-std"]
keywords = ["ml-kem", "fips-203", "kem", "post-quantum", "lattice-based"]
exclude = ["tests/"]

[lints]
workspace = true

[dependencies]
backbone-pqcrypto-internals = { version = "0.2.1", path = "../backbone-pqcrypto-internals", default-features = false }
zeroize = { workspace = true }
sha3 = { workspace = true }
getrandom = { workspace = true }
subtle = { workspace = true }
rand_core = { workspace = true }

[features]
default = ["std"]
std = ["alloc", "sha3/std", "backbone-pqcrypto-internals/std", "getrandom/std"]
alloc = []

[dev-dependencies]
sha2 = { workspace = true }
