[package]
name = "backbone-sphincs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "SPHINCS+ (FIPS 205) implementation: Stateless Hash-Based Digital Signature Standard."
categories = ["cryptography", "no-std"]
keywords = ["sphincs+", "fips-205", "signature", "post-quantum", "hash-based"]
exclude = ["tests/"]

[lints]
workspace = true

[dependencies]
backbone-pqcrypto-internals = { version = "0.2.1", path = "../backbone-pqcrypto-internals", default-features = false }
zeroize = { workspace = true }
getrandom = { workspace = true }
rand_core = { workspace = true }

# Address encoding, HMAC, hash functions
zerocopy = { version = "0.8", features = ["derive"] }
hmac = "0.13"
shake = "0.1"
sha2 = "0.11"
digest = "0.11"
sha3 = { workspace = true }

[features]
default = ["std"]
std = [
  "alloc",
  "sha2/alloc",
  "sha3/std",
  "backbone-pqcrypto-internals/std",
  "getrandom/std",
]
alloc = []
