[package]
name = "backbone-hqc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "HQC (FIPS 207) implementation: Hamming Quasi-Cyclic KEM."
categories = ["cryptography", "no-std"]
keywords = ["hqc", "fips-207", "kem", "post-quantum", "code-based"]
exclude = ["tests/"]

[lints]
workspace = true

[dependencies]
safe_arch = { version = "1", optional = true }
backbone-pqcrypto-internals = { version = "0.2.1", path = "../backbone-pqcrypto-internals", default-features = false }
subtle = { workspace = true }
zeroize = { workspace = true }
sha3 = { workspace = true, default-features = false }
getrandom = { workspace = true }
rand_core = { workspace = true }

[features]
default = ["std"]
std = [
  "alloc",
  "sha3/std",
  "backbone-pqcrypto-internals/std",
  "getrandom/std",
]
alloc = []
simd = ["safe_arch"]
