[package]
name = "pqcrypto-ml-kem"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "ML-KEM (FIPS 203) implementation: Module-Lattice-Based Key Encapsulation Mechanism"
categories = ["cryptography", "no-std"]
keywords = ["ml-kem", "fips-203", "kem", "post-quantum", "lattice-based"]

[lints]
workspace = true

[dependencies]
safe_arch = { version = "1", optional = true }
pqcrypto-utils = { path = "../pqcrypto-utils", default-features = false }
zeroize = { workspace = true }
sha3 = { workspace = true }
getrandom = { workspace = true }
subtle = { workspace = true }

[features]
default = ["std", "zeroize"]
std = ["alloc", "sha3/std", "zeroize/alloc", "pqcrypto-utils/std", "getrandom/std"]
alloc = ["zeroize/alloc"]
zeroize = ["pqcrypto-utils/zeroize"]
simd = ["safe_arch"]

[dev-dependencies]
sha2 = { workspace = true }
